<a href="https://colab.research.google.com/github/DunjaPawlovic/product-category-classification/blob/main/notebook/01_eda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

url = "https://raw.githubusercontent.com/DunjaPawlovic/product-category-classification/main/data/products.csv"

df = pd.read_csv(url)

df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35311 entries, 0 to 35310
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   product ID       35311 non-null  int64
 1   Product Title    35139 non-null  object
 2   Merchant ID      35311 non-null  int64
 3    Category Label  35267 non-null  object
 4   _Product Code    35216 non-null  object
 5   Number_of_Views  35297 non-null  float64
 6   Merchant Rating  35141 non-null  float64
 7    Listing Date    35252 non-null  object
dtypes: float64(2), int64(2), object(4)
memory usage: 2.2+ MB

In [3]:
df.isnull().sum()

product ID           0
Product Title      172
Merchant ID          0
 Category Label     44
_Product Code       95
Number_of_Views     14
Merchant Rating    170
 Listing Date       59
dtype: int64

In [5]:
df.columns

Index(['product ID', 'Product Title', 'Merchant ID', ' Category Label',
       '_Product Code', 'Number_of_Views', 'Merchant Rating',
       ' Listing Date  '],
      dtype='object')

In [6]:
df.columns = df.columns.str.strip()

In [7]:
df.columns

Index(['product ID', 'Product Title', 'Merchant ID', 'Category Label',
       '_Product Code', 'Number_of_Views', 'Merchant Rating', 'Listing Date'],
      dtype='object')

In [8]:
df_clean = df.dropna(subset=["Category Label", "Product Title"])

In [9]:
df_clean.isnull().sum()

product ID           0
Product Title        0
Merchant ID          0
Category Label       0
_Product Code       94
Number_of_Views     14
Merchant Rating    170
Listing Date        58
dtype: int64

In [10]:
len(df), len(df_clean)

(35311, 35096)

In [11]:
X = df_clean["Product Title"]
y = df_clean["Category Label"]

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words="english")
X_vec = vectorizer.fit_transform(X)

In [13]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_vec, y, test_size=0.2, random_state=42
)

In [14]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [15]:
model.score(X_test, y_test)

0.9468660968660969

In [16]:
y_pred = model.predict(X_test)

In [17]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

array([[   0,   14,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0],
       [   0,  724,    0,    0,    0,    0,    1,    0,    0,    0,    0,
           1,    0],
       [   0,    0,  531,    0,    0,    0,    0,    0,    0,    4,    0,
           0,    0],
       [   0,    0,    0,  650,    0,    3,   18,    0,    0,    2,    0,
          11,    0],
       [   0,    0,    0,    4,  361,   10,   40,    0,    0,    1,    0,
           6,    0],
       [   0,    0,    0,   27,    0, 1008,   40,    0,    0,    1,    3,
           8,    0],
       [   0,    0,    0,    8,    3,   35,  646,    0,    0,    1,    2,
           7,    0],
       [   0,    0,    2,   11,    0,    0,    3,  441,    0,    2,    2,
           3,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,   17,    0,
           0,    0],
       [   0,    0,    1,    0,    0,    0,    0,    0,    0,  784,   10,
           0,    0],
       [   0,    0,    3,    0,    0,    0,    0,    1,    0,    8,  712,
           0,    0],
       [   0,    0,    0,   12,    0,    2,    5,    2,    0,    4,    6,
         790,    0],
       [   0,    0,    0,    2,    0,    3,   23,    0,    0,    0,    0,
           1,    0]])

In [18]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

                  precision    recall  f1-score   support

             CPU       0.00      0.00      0.00        14
            CPUs       0.98      1.00      0.99       726
 Digital Cameras       0.99      0.99      0.99       535
     Dishwashers       0.91      0.95      0.93       684
        Freezers       0.99      0.86      0.92       422
 Fridge Freezers       0.95      0.93      0.94      1087
         Fridges       0.83      0.92      0.87       702
      Microwaves       0.99      0.95      0.97       464
    Mobile Phone       0.00      0.00      0.00        17
   Mobile Phones       0.95      0.99      0.97       795
             TVs       0.97      0.98      0.98       724
Washing Machines       0.96      0.96      0.96       821
          fridge       0.00      0.00      0.00        29

        accuracy                           0.95      7020
       macro avg       0.73      0.73      0.73      7020
    weighted avg       0.94      0.95      0.94      7020

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [19]:
import pickle

with open("model.pkl", "wb") as f:
    pickle.dump(model, f)